spring:
  config:
    import: "classpath:environments/"

llm:
  api:
    scheme: http
    host: localhost
    port: 11434
    model: phi3
    endpoint: api/generate
  prompt:
    default_path: src/main/java/org/testinfra/llm//test_fail_llm_prompt_template.txt