jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

tool:
  jdk:
    installations:
      - name: "jdk21"
        home: "/opt/java/openjdk"
  maven:
    installations:
      - name: "maven-3.9.11"
        home: "/opt/maven"
        properties: [ ]

jobs:
  - script: >
      pipelineJob('test-automation-demo') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/DmitriMalamoud/DimaAutomationDemo.git')
                }
                branch('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }